version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: enzo-privatebin
      APP_PORT: 8081
  server:
    container_name: enzo-privatebin
    image: privatebin/nginx-fpm-alpine
    volumes:
      - ${APP_DATA_DIR}/privatebin-data:/srv/data
    ports:
      - "8081:8081"
    restart: unless-stopped