services:
  app_proxy:
    environment:
      APP_HOST: enzo-puter
      APP_PORT: 4100
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/heyputer/puter:latest
    restart: on-failure
    environment:
      TZ: "Europe/Berlin"
      PUID: "1000"
      PGID: "1000"
      HOST: "0.0.0.0"
    volumes:
      - ${APP_DATA_DIR}/data:/data/.puter
      - ${APP_DATA_DIR}/config:/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s