version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: enzo-owntown
      APP_PORT: 3689

  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: enzo-owntone
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ${APP_DATA_DIR}/etc/owntone:/etc/owntone
      - ${APP_DATA_DIR}/mnt/media:/srv/media
      - ${APP_DATA_DIR}/var/cache/owntone:/var/cache/owntone
    ports:
      - "3689:3689"
    restart: unless-stopped