services:
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: enzo-owntone
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./etc/owntone:/etc/owntone
      - ./mnt/media:/srv/media
      - ./var/cache/owntone:/var/cache/owntone
    ports:
      - "3689:3689"
    restart: unless-stopped