version: "3"
services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - ${HOMEDIR}/music:/music
      - ${APP_DATA_DIR}/config:/config
    ports:
      - "1970:1970"
    restart: unless-stopped