version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: enzo-swingmusic
      APP_PORT: 1970
  server:
    container_name: enzo-swingmusic
    image: ghcr.io/swingmx/swingmusic:latest
    volumes:
      - ~/music:/music
      - ${APP_DATA_DIR}/config:/config
    ports:
      - "1970:1970"
    restart: unless-stopped