services:
  dashdot:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    container_name: dashdot
    privileged: true
    ports:
      - 3001:3001
    volumes:
      - ./dashbot:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=false
      - DASHDOT_SHOW_DASH_VERSION=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_USE_IMPERIAL=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=dashdot
      - DASHDOT_ACCEPT_OOKLA_EULA=true