---
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: enzo-pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RATE_LIMIT=false #optional
      - WS_FALLBACK=false #optional
      - RTC_CONFIG= #optional
      - DEBUG_MODE=false #optional
    ports:
      - 3099:3000
    restart: unless-stopped

  app_proxy:
    environment:
      APP_HOST: enzo-pairdrop_server_1
      APP_PORT: 3099
      PROXY_AUTH_ADD: "false"