services:
  dokemon:
    image: productiveops/dokemon:latest
    container_name: enzo-dokemon
    ports:
      - "9990:9090"
    volumes:
      - ${APP_DATA_DIR}/dokemondata:/data
      - var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped